version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: gonexus-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: gonexus
      MYSQL_USER: gonexus
      MYSQL_PASSWORD: gonexus123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  mysql_data:
